name: "chronograf/cypress"

on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      # Our Enterprise chart requires some resources created
      - name: Create Enterprise Test Resources
        run: |
          kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
          sleep 30 # wait for CertManager
          kubectl apply -f https://raw.githubusercontent.com/influxdata/helm-charts/master/charts/influxdb-enterprise/example-resources.yaml
          kubectl create secret generic influxdb-license --from-literal=INFLUXDB_ENTERPRISE_LICENSE_KEY=${INFLUXDB_ENTERPRISE_LICENSE_KEY}
        env:
          INFLUXDB_ENTERPRISE_LICENSE_KEY: "${{ secrets.INFLUXDB_ENTERPRISE_LICENSE_KEY }}"
        if: steps.list-changed.outputs.changed == 'true'
